---
- hosts: 'proxmox'
  tasks:
    - ansible.builtin.ping: {}

- hosts: 'proxmox'
  roles:
    - role: 'infothrill.rpi_boot_config'
      vars:
        boot_config_lines:
          - 'dtparam=i2c_arm=on,i2c_arm_baudrate=400000'
          - 'dtoverlay=gpio-shutdown,gpio_pin=4,active_low=1,gpio_pull=up'
  tasks:
    - community.general.modprobe:
        name: 'i2c-dev'
    - ansible.builtin.apt:
        name: 'git'
    - ansible.builtin.git:
        repo: 'https://github.com/UCTRONICS/SKU_RM0004.git'
        dest: '/opt/uctronics/sku_rm0004'
    - ansible.builtin.shell:
        chdir: '/opt/uctronics/sku_rm0004'
        cmd: 'make'
        creates: '/opt/uctronics/sku_rm0004/display'
    - ansible.builtin.shell: 'nohup /opt/uctronics/sku_rm0004/display >/dev/null 2>&1 &'

- hosts: 'proxmox'
  tasks:
    - name: 'Set hostname'
      block:
        - ansible.builtin.hostname:
            name: '{{ inventory_hostname }}'
        - ansible.builtin.template:
            src: 'hosts.j2'
            dest: '/etc/hosts'

    - name: 'Install proxmox'
      block:
        - ansible.builtin.apt_key:
            url: 'https://raw.githubusercontent.com/pimox/pimox7/master/KEY.gpg'
        - ansible.builtin.apt_repository:
            filename: 'pimox'
            repo: 'deb https://raw.githubusercontent.com/pimox/pimox7/master/ dev/'
        - ansible.builtin.apt:
            name: 'proxmox-ve'
