---
- name: 'Configure UCTRONICS RM0004'
  hosts: 'proxmox'
  roles:
    - role: 'infothrill.rpi_boot_config'
      vars:
        boot_config_lines:
          - 'dtparam=i2c_arm=on,i2c_arm_baudrate=400000'
          - 'dtoverlay=gpio-shutdown,gpio_pin=4,active_low=1,gpio_pull=up'
  tasks:
    - name: 'Enable kernel modules'
      community.general.modprobe:
        name: 'i2c-dev'
    - name: 'Install prerequisites'
      ansible.builtin.apt:
        name: 'git'
    - name: 'Download display driver'
      ansible.builtin.git:  # noqa: latest
        repo: 'https://github.com/UCTRONICS/SKU_RM0004.git'
        dest: '/opt/uctronics/sku_rm0004'
    - name: 'Compile display driver'
      ansible.builtin.command:
        chdir: '/opt/uctronics/sku_rm0004'
        cmd: 'make'
        creates: '/opt/uctronics/sku_rm0004/display'
    - name: 'Run display driver'
      ansible.builtin.shell: 'nohup /opt/uctronics/sku_rm0004/display >/dev/null 2>&1 &'  # noqa: no-changed-when

- name: 'Install Pimox'
  hosts: 'proxmox'
  tasks:
    - name: 'Set hostname'
      block:
        - name: 'Configure hostname'
          ansible.builtin.hostname:
            name: '{{ inventory_hostname }}'
        - name: 'Configure /etc/hosts'
          ansible.builtin.template:
            src: 'hosts.j2'
            dest: '/etc/hosts'
            mode: '0644'

    - name: 'Install proxmox'
      block:
        - name: 'Install proxmox key'
          ansible.builtin.apt_key:
            url: 'https://raw.githubusercontent.com/pimox/pimox7/master/KEY.gpg'
        - name: 'Install proxmox repository'
          ansible.builtin.apt_repository:
            filename: 'pimox'
            repo: 'deb https://raw.githubusercontent.com/pimox/pimox7/master/ dev/'
        - name: 'Install proxmox package'
          ansible.builtin.apt:
            name: 'proxmox-ve'
