---
- hosts: 'proxmox'
  tasks:
    - ansible.builtin.ping: {}
  
    - name: 'Set hostname'
      block:
        - ansible.builtin.hostname:
            name: '{{ inventory_hostname }}'
        - ansible.builtin.template:
            src: 'hosts.j2'
            dest: '/etc/hosts'

    - name: 'Install proxmox'
      block:
        - ansible.builtin.apt_key:
            url: 'https://raw.githubusercontent.com/pimox/pimox7/master/KEY.gpg'
        - ansible.builtin.apt_repository:
            filename: 'pimox'
            repo: 'deb https://raw.githubusercontent.com/pimox/pimox7/master/ dev/'
        - ansible.builtin.apt:
            name: 'proxmox-ve'
