---
- name: 'Restart HAProxy'
  ansible.builtin.systemd_service:
    name: 'haproxy'
    state: 'restarted'
  become: true

- name: 'Reload systemctl daemon'
  ansible.builtin.systemd_service:
    daemon_reload: true
  become: true

- name: 'Reload udevadm'
  ansible.builtin.command: 'udevadm control --reload-rules'
  become: true
- name: 'Trigger udevadm'
  ansible.builtin.command: 'udevadm trigger'
  become: true
