---
- name: 'haproxy restart'
  ansible.builtin.systemd_service:
    name: 'haproxy'
    state: 'restarted'
  become: true

- name: 'systemctl daemon-reload'
  ansible.builtin.systemd_service:
    daemon_reload: true
  become: true

- name: 'udevadm reload'
  ansible.builtin.command: 'udevadm control --reload-rules'
  become: true
- name: 'udevadm trigger'
  ansible.builtin.command: 'udevadm trigger'
  become: true
