---
- name: 'Configure SSH'
  become: true
  block:
    - name: 'Add the authorized keys'
      ansible.posix.authorized_key:
        user: '{{ common_ssh_user }}'
        key: '{{ common_ssh_authorized_keys }}'
        exclusive: false

    - name: 'Harden the SSH daemon'
      ansible.builtin.copy:
        dest: '/etc/ssh/sshd_config.d/10-hardening.conf'
        content: |
          KbdInteractiveAuthentication {{ 'yes' if common_ssh_password_authentication else 'no' }}
          PasswordAuthentication {{ 'yes' if common_ssh_password_authentication else 'no' }}
          PermitRootLogin {{ 'yes' if common_ssh_permit_root_login else 'no' }}
        owner: 'root'
        group: 'root'
        mode: '0644'
        validate: '/usr/sbin/sshd -t -f %s'
      notify: 'Restart SSH'
