---
github_runner_architecture: '{{ github_runner_architectures[ansible_facts.architecture] }}'
github_runner_archive: 'actions-runner-linux-{{ github_runner_architecture }}-{{ github_runner_version }}.tar.gz'
github_runner_checksum: '{{ github_runner_checksums[github_runner_architecture] }}'
github_runner_configuration:
  labels: '{{ github_runner_labels }}'
  name: '{{ github_runner_name }}'
  repository: '{{ github_runner_repository }}'
github_runner_configuration_path: '{{ github_runner_directory }}/.ansible-configuration.json'
github_runner_directory: '/opt/github/actions-runner'
github_runner_labels:
  - 'homelab'
  - '{{ github_runner_architecture }}'
github_runner_name: '{{ inventory_hostname }}'
github_runner_release: 'https://github.com/actions/runner/releases/download/v{{ github_runner_version }}'
github_runner_service: 'actions.runner.{{ github_runner_repository | replace("/", "-") }}.{{ github_runner_name }}.service'
github_runner_user: 'github-runner'
github_runner_version_path: '{{ github_runner_directory }}/.ansible-version-{{ github_runner_version }}'

github_runner_version: '2.337.0'
github_runner_architectures:
  aarch64: 'arm64'
  armv6l: 'arm'
  armv7l: 'arm'
  x86_64: 'x64'
github_runner_checksums:
  arm: 'sha256:3ea05289b7f7e1bc9a7bb35e2f738a903e0f757cb27ed32a3ef701404cf6d8e8'
  arm64: 'sha256:9b1dc70626422526e3c94767cf024896beb15da5342a3f4819bf2feac13e0393'
  x64: 'sha256:70920811a4f8ad4328818682bca5c6469c1c942fab52448868071d0063816613'
