---
- name: 'Setup the GitHub Actions runners'
  hosts: 'github_runners'
  roles:
    - role: 'common'
    - role: 'claude_daemon'
    - role: 'github_cli'
    - role: 'github_runner'
      vars:
        github_runner_access_token: '{{ lookup("pipe", "gh auth token") }}'
        github_runner_group: 'Homelab'
        github_runner_organization: 'spence-com-au'
        github_runner_version: '2.337.0'
