---
- name: 'Setup the GitHub Actions runners'
  hosts: 'github_runners'
  vars:
    github_runner_user: 'github-runner'
  roles:
    - role: 'common'
    - role: 'claude_daemon'
    - role: 'github_runner'
    - role: 'monolithprojects.github_actions_runner'
      vars:
        access_token: '{{ lookup("pipe", "gh auth token") }}'
        github_account: 'spence-com-au'
        runner_dir: '/opt/github/actions-runner'
        runner_group: 'Homelab'
        runner_labels:
          - 'homelab'
        runner_name: '{{ inventory_hostname }}'
        runner_org: true
        runner_user: '{{ github_runner_user }}'
        runner_version: '2.337.0'
